Updated Orca4 SDF file to use BlueROV2 models
clydemcqueen/orca4 pull request #10
Opened 2023-06-29 18:50 UTC by ssicari

2023-06-30 16:09 UTC, clydemcqueen commented
Very cool! I ran this and it looks and works great.

I'd like to see the changes made to the model.sdf.in and the generator script (generate_model.py) such that when you run the script you get the correct results in model.sdf. That way it is easy to change the generator script to experiment with different parameters.

See the changes made to bluerov2_ignition for an example: https://github.com/clydemcqueen/bluerov2_ignition/pull/6/files

2023-06-30 16:47 UTC, ssicari commented
> Very cool! I ran this and it looks and works great.
> 
> I'd like to see the changes made to the model.sdf.in and the generator script (generate_model.py) such that when you run the script you get the correct results in model.sdf. That way it is easy to change the generator script to experiment with different parameters.
> 
> See the changes made to bluerov2_ignition for an example: https://github.com/clydemcqueen/bluerov2_ignition/pull/6/files

I made the changes based on the link example. I am a little confused on what exactly those changes are for and what exactly the generator script and model.sdf.in do. If you could give me a more in explanation that would be appreciated. Let me know if I need to make more changes, thank you!

2023-07-01 15:03 UTC, clydemcqueen commented
I use generator.py to re-write orca4/model.sdf from orca4/model.sdf.in, replacing strings like "@camera_y" with the result of the expression "stereo_baseline / 2". This makes it easy to build models with different camera placements and so forth.

To modify the model, update model.sdf.in and then run generate.py:
~~~
cd orca_description
scripts/generate_model.py models/orca4/model.sdf.in models/orca4/model.sdf 0 
~~~

2023-07-01 15:08 UTC, clydemcqueen requested changes

2023-07-01 15:08 UTC, clydemcqueen commented on orca_description/models/orca4/model.sdf.in
> -    <!-- Left camera link -->
The camera links, joints and sensors are required. Please restore.

2023-07-01 15:08 UTC, clydemcqueen commented on orca_description/scripts/generate_model.py
> -# MIT License
Please restore the license.

2023-07-01 15:08 UTC, clydemcqueen commented on orca_description/scripts/generate_model.py
> -We use the COMMAND method to send commands to the Gazebo Sim ThrusterPlugin. The ThrusterPlugin
The new Gazebo is called "Gazebo Sim" to distinguish it from the old Gazebo.

2023-07-01 15:08 UTC, clydemcqueen commented on orca_description/scripts/generate_model.py
> -# Stereo camera
The camera section is required.

2023-07-01 20:57 UTC, ssicari commented
> I use generator.py to re-write orca4/model.sdf from orca4/model.sdf.in, replacing strings like "@camera_y" with the result of the expression "stereo_baseline / 2". This makes it easy to build models with different camera placements and so forth.
> 
> To modify the model, update model.sdf.in and then run generate.py:
> 
> ```
> cd orca_description
> scripts/generate_model.py models/orca4/model.sdf.in models/orca4/model.sdf 0 
> ```

I made the changes you requested, that was my fault when I was copying and pasting I must have not been paying close enough attention to differences between the files. I appreciate the responses it has cleared up some confusion as well.

2023-07-02 14:09 UTC, clydemcqueen reviewed
Yes, that is how the generator works. I should just remove orca4/model.sdf from the repo and generate it from orca4/model.sdf.in during the build step. I'll do this in another PR.

This is useful for avoiding copy/paste errors while experimenting with the model. It is easy to change the max thrust or mass or stereo baseline, then re-run the generator and the sdf file is updated.

Two typos, then this is done!

Thanks for this great contribution to orca4!

2023-07-02 16:07 UTC, ssicari commented
> Yes, that is how the generator works. I should just remove orca4/model.sdf from the repo and generate it from orca4/model.sdf.in during the build step. I'll do this in another PR.
> 
> This is useful for avoiding copy/paste errors while experimenting with the model. It is easy to change the max thrust or mass or stereo baseline, then re-run the generator and the sdf file is updated.
> 
> Two typos, then this is done!
> 
> Thanks for this great contribution to orca4!

Should be all set now, thank you!

2023-07-02 16:26 UTC, clydemcqueen approved these changes

2023-07-02 16:26 UTC, merged